name: Node.js CI
on:
  - pull_request
  - push
  - workflow_dispatch
 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with: 
          cache: 'npm'
      - name: 'Use Node.js ${{ matrix.node-version }}'
        uses: actions/setup-node@v3
        with:
          node-version: '21'
          cache: npm
      - name: Install Dependency npm-install
        run: |
          npm ci
          sudo apt-get install xvfb
      - name: Run Nightwatch tests
        run: xvfb-run --auto-servernum npm test -- --env chrome
       # Step to capture test results as artifacts
      - name: Archive test results
        if: always()  # Ensure this step runs even if the previous steps fail
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: tests_output 
      - name: Send notifications
        if: failure() 
        run: |
          # Add your notification mechanism here (e.g., sending an email, Slack message)
          echo "Test failures occurred. Please check the test reports for details."
